FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Content Manager

END POINT API Content Manager

## API Version
* /conm/v1

## Metadata Content [/]

___
***Table Routes:***
| URL                     | Method | INFO                    |
| ----------------------- | ------ | -----------------------|
| `/`                     | GET    | Get All Metadata       |
| `/{id}`                 | GET    | Get Metadata By Id     |
| `/store`                | POST   | Save Metadata          |
| `/delete/{id}`          | GET    | Delete Metadata        |
| `/update/{id}`          | POST   | Update Metadata By Id  |

___
**Save Metadata Parameter:**
| Parameter           | type   | Status   | Description                   |
| --------------------| ------ | -------- | ------------------------------|
| `user_id`           | uuid   | required | User ID                       |
| `video_title`       | string | required | Title of Video                |
| `video_description` | string | required | Description of Video          |
| `video_genre`       | string | required | Genre of Video                |
| `privacy`           | string | required | privacy video(public/private) |

___
**Update Metadata By Id:**
| Parameter           | type   | Status   | Description                   |
| --------------------| ------ | -------- | ------------------------------|
| `video_title`       | string | optimal  | Title of Video                |
| `video_description` | string | optimal  | Description of Video          |
| `video_genre`       | string | optimal  | Genre of Video                |
| `privacy`           | string | optimal  | privacy video(public/private) |

### Get All Metadata [GET /{id}]

+ Response 200 (application/json)

        {
            "status": {
                "code": "200",
                "message": "index list query has been performed, data has been found",
                "total": 1
            },
            "result": [
                {
                    "metavideos": [
                        {
                            "duration": 30,
                            "file_path": "/videos/1080p/tutorial-node-js-bagian-1.mp4",
                            "size": 104857600,
                            "updated_at": "2019-08-24T22:28:16+07:00",
                            "file_name": "tutorial-node-js-bagian-1.mp4",
                            "format": "mp4",
                            "created_at": "2019-08-24T22:28:16+07:00",
                            "id": "cb92f773-c0a9-41dc-8cc9-9be9d680097c",
                            "resolution": "1080p"
                        }
                    ],
                    "comments": null,
                    "privacy": "public",
                    "created_at": "2019-08-24T22:34:32+07:00",
                    "video_share": null,
                    "dislikes": null,
                    "video_downloads": null,
                    "video_description": "Tutorial Dasar NodeJs",
                    "category_id": "2f0a68a1-115d-4c24-9173-404638a1fc27",
                    "video_title": "Tutorial NodeJs - Bagian 1",
                    "updated_at": "2019-08-24T22:34:32+07:00",
                    "user_id": "91fa1120-17d4-442b-8338-aa3ab7bbc14e",
                    "subtitle": null,
                    "video_genre": "Tutorial",
                    "id": "56b140a1-16a7-4fbb-b852-7365fbff7112",
                    "video_saves": null,
                    "video_viewers": null,
                    "likes": null
                }
            ]
        }

## Content Categoritation [/category]

### Get Metadata By Category Id [GET /category/{id}]

+ Parameter
    + id: `bae04ac0-234a-431a-bed4-0bbc7026aa1c` (string, required) - category_id of Content Metadata
    
+ Response 200 (application/json)

        {
            "status" : {
                "code" : 200,
                "message" : "search query has been peformed, data has been found",
                "total" : 1
            },
            "result" : [
                {
                    "metavideos": [
                        {
                            "duration": 30,
                            "file_path": "/videos/1080p/tutorial-node-js-bagian-1.mp4",
                            "size": 104857600,
                            "updated_at": "2019-08-24T22:28:16+07:00",
                            "file_name": "tutorial-node-js-bagian-1.mp4",
                            "format": "mp4",
                            "created_at": "2019-08-24T22:28:16+07:00",
                            "id": "cb92f773-c0a9-41dc-8cc9-9be9d680097c",
                            "resolution": "1080p"
                        }
                    ],
                    "comments": null,
                    "privacy": "public",
                    "created_at": "2019-08-24T22:34:32+07:00",
                    "video_share": null,
                    "dislikes": null,
                    "video_downloads": null,
                    "video_description": "Tutorial Dasar NodeJs",
                    "category_id": "2f0a68a1-115d-4c24-9173-404638a1fc27",
                    "video_title": "Tutorial NodeJs - Bagian 1",
                    "updated_at": "2019-08-24T22:34:32+07:00",
                    "user_id": "91fa1120-17d4-442b-8338-aa3ab7bbc14e",
                    "subtitle": null,
                    "video_genre": "Tutorial",
                    "id": "56b140a1-16a7-4fbb-b852-7365fbff7112",
                    "video_saves": null,
                    "video_viewers": null,
                    "likes": null
                }
            ]
        }